### ISSUE TITLE
Issue with re-entry of correct letter

### ISSUE THREAD

**Issue by Akamoha** [VamsiYS/Hangman#1]
If a user enters a correct letter, say 'A', and then later enters that letter again (by mistake or just to be a pain in the rear), the program counts it as a wrong letter and a life is lost.

**Comment by VamsiYS** [comment]
Yes. I know of this. Need to make some changes. BTW, it doesn't reduce the number of lives. It just does nothing. However, I'll edit it soon. Thanks
